

# H2 in-file
spring.datasource.url=jdbc:h2:file:./data/wallet;MODE=PostgreSQL;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Flyway  H2
spring.flyway.url=jdbc:h2:file:./data/wallet;MODE=PostgreSQL;AUTO_SERVER=TRUE
spring.flyway.user=sa
spring.flyway.password=

spring.jpa.hibernate.ddl-auto=validate

APP_JWT_SECRET: "VGhpc0lzQURldkRTZWNyZXQxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMw=="
APP_JWT_EXP: "7200"