spring.application.name=wallet

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
app.jwt.ttl-hours=6


# JPA
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.springframework.security=DEBUG
