spring.application.name=wallet
spring.docker.compose.enabled=false

# ----- Profiles -----
spring.profiles.active=dev

# JWT
app.jwt.secret=G7h1JbJ5C0nq2pW8zKzq6Vt2z6r0y9n3w5r8u1s4x7y0z3p6q9t2w5y8z1x4v7
app.jwt.ttl-hours=6


# ----- H2 (dev) -----
spring.datasource.url=jdbc:h2:mem:wallet;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# spring.jpa.show-sql=true
# logging.level.org.hibernate.SQL=debug
# logging.level.org.hibernate.orm.jdbc.bind=trace

#----- Swagger--------
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tryItOutEnabled=true
