

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet
spring.datasource.username=wallet
spring.datasource.password=wallet

# Flyway
spring.flyway.url=jdbc:postgresql://localhost:5432/wallet
spring.flyway.user=wallet
spring.flyway.password=wallet
spring.jpa.hibernate.ddl-auto=validate

# JWT secret  ENV
app.jwt.secret=${JWT_SECRET}
