CREATE TABLE audit_log
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ts         TIMESTAMP                               NOT NULL,
    username   VARCHAR(64)                             NOT NULL,
    operation  VARCHAR(32)                             NOT NULL,
    amount     DECIMAL(18, 2),
    ref        VARCHAR(100),
    details    VARCHAR(200),
    request_id VARCHAR(40),
    CONSTRAINT pk_audit_log PRIMARY KEY (id)
);

CREATE TABLE ledger
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version    INT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    wallet_id  BIGINT                                  NOT NULL,
    amount     DECIMAL(18, 2)                          NOT NULL,
    type       VARCHAR(20)                             NOT NULL,
    ref        VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_ledger PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version       INT,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    username      VARCHAR(64)                             NOT NULL,
    password_hash VARCHAR(200)                            NOT NULL,
    roles         VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE wallet
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version    INT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    user_id    BIGINT                                  NOT NULL,
    balance    DECIMAL(18, 2)                          NOT NULL,
    CONSTRAINT pk_wallet PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE wallet
    ADD CONSTRAINT uc_wallet_user UNIQUE (user_id);

CREATE INDEX ix_audit_ts ON audit_log (ts);

CREATE INDEX ix_audit_user ON audit_log (username);

CREATE INDEX ix_ledger_ref ON ledger (ref);

CREATE UNIQUE INDEX ix_ledger_wallet_ref ON ledger (wallet_id, ref);

ALTER TABLE ledger
    ADD CONSTRAINT FK_LEDGER_ON_WALLET FOREIGN KEY (wallet_id) REFERENCES wallet (id);

ALTER TABLE wallet
    ADD CONSTRAINT FK_WALLET_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);