-- === USERS ================================================================
create table if not exists users (
                                     id            bigint generated by default as identity primary key,
                                     version       int,
                                     username      varchar(64)  not null unique,
    password_hash varchar(200) not null,
    roles         varchar(100) not null,
    created_at    timestamp,
    updated_at    timestamp
    );

-- === WALLET ========================================================
create table if not exists wallet (
                                      id         bigint generated by default as identity primary key,
                                      version    int,
                                      user_id    bigint not null unique,
                                      balance    numeric(18,2) not null default 0,
    created_at timestamp,
    updated_at timestamp,
    constraint fk_wallet_user
    foreign key (user_id) references users(id)
    );

-- === LEDGER ============================================================
create table if not exists ledger (
                                      id         bigint generated by default as identity primary key,
                                      version    int,
                                      wallet_id  bigint not null,
                                      amount     numeric(18,2) not null,
    type       varchar(20)   not null,   -- DEPOSIT / TRANSFER_IN / TRANSFER_OUT
    ref        varchar(100)  not null,   -- برای idempotency و ردیابی
    created_at timestamp,
    updated_at timestamp,
    constraint fk_ledger_wallet
    foreign key (wallet_id) references wallet(id)
    );

create unique index if not exists ix_ledger_wallet_ref on ledger(wallet_id, ref);
create index if not exists ix_ledger_ref on ledger(ref);

-- === AUDIT_LOG =====================================================
create table if not exists audit_log (
                                         id          bigint generated by default as identity primary key,
                                         ts          timestamp not null,
                                         username    varchar(64) not null,
    action      varchar(32) not null,
    amount      numeric(18,2),
    ref         varchar(100),
    details     varchar(200),
    request_id  varchar(40)
    );

create index if not exists ix_audit_ts   on audit_log(ts);
create index if not exists ix_audit_user on audit_log(username);
