-- V2__account_limits.sql
-- Account limit tables (config + usage)
-- Compatible with H2 and PostgreSQL

/* =======================
   ACCOUNT_LIMIT_CONFIG
   one-to-one per user
   ======================= */
CREATE TABLE IF NOT EXISTS ACCOUNT_LIMIT_CONFIG (
                                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                    created_at        TIMESTAMP,
                                                    updated_at        TIMESTAMP,
                                                    version           BIGINT,

                                                    user_id           BIGINT NOT NULL UNIQUE,
                                                    daily_limit       DECIMAL(19,2) NOT NULL,
    single_tx_limit   DECIMAL(19,2) NOT NULL,

    CONSTRAINT fk_alc_user
    FOREIGN KEY (user_id) REFERENCES USERS (id)
    );

/* helpful index (unique already exists on user_id) */
CREATE INDEX IF NOT EXISTS ix_alc_user_id ON ACCOUNT_LIMIT_CONFIG(user_id);

/* =======================
   ACCOUNT_LIMIT_USAGE
   one row per user per day
   ======================= */
CREATE TABLE IF NOT EXISTS ACCOUNT_LIMIT_USAGE (
                                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   created_at   TIMESTAMP,
                                                   updated_at   TIMESTAMP,
                                                   version      BIGINT,

                                                   user_id      BIGINT NOT NULL,
                                                   date         DATE   NOT NULL,
                                                   used_amount  DECIMAL(19,2) NOT NULL DEFAULT 0.00,
    last_tx_id   UUID,

    CONSTRAINT uq_alu_user_day UNIQUE (user_id, date),
    CONSTRAINT fk_alu_user
    FOREIGN KEY (user_id) REFERENCES USERS (id)
    );

/* indexes */
CREATE INDEX IF NOT EXISTS ix_alu_user_id ON ACCOUNT_LIMIT_USAGE(user_id);
CREATE INDEX IF NOT EXISTS ix_alu_date     ON ACCOUNT_LIMIT_USAGE(date);
