
-- =========================
-- DROP (ignore errors)
-- =========================
DROP INDEX IF EXISTS ix_ledger_wallet_ref;
DROP INDEX IF EXISTS ix_ledger_ref;
DROP INDEX IF EXISTS ix_audit_user;

ALTER TABLE LEDGER                DROP CONSTRAINT IF EXISTS FK_LEDGER_WALLET;
ALTER TABLE WALLET                DROP CONSTRAINT IF EXISTS FK_WALLET_USER;
ALTER TABLE ACCOUNT_LIMIT_CONFIG  DROP CONSTRAINT IF EXISTS FK_ALC_USER;
ALTER TABLE ACCOUNT_LIMIT_USAGE   DROP CONSTRAINT IF EXISTS FK_ALU_USER;

DROP TABLE IF EXISTS LEDGER;
DROP TABLE IF EXISTS WALLET;
DROP TABLE IF EXISTS ACCOUNT_LIMIT_USAGE;
DROP TABLE IF EXISTS ACCOUNT_LIMIT_CONFIG;
DROP TABLE IF EXISTS AUDIT_LOG;
DROP TABLE IF EXISTS USERS;

-- =========================
-- CREATE TABLES
-- =========================


CREATE TABLE USERS (
                       ID            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       VERSION       INT,
                       CREATED_AT    TIMESTAMP,
                       UPDATED_AT    TIMESTAMP,

                       USERNAME      VARCHAR(64)  NOT NULL UNIQUE,
                       PASSWORD_HASH VARCHAR(200) NOT NULL,
                       ROLES         VARCHAR(100) NOT NULL
);

CREATE TABLE WALLET (
                        ID         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        VERSION    INT,
                        CREATED_AT TIMESTAMP,
                        UPDATED_AT TIMESTAMP,

                        USER_ID    BIGINT      NOT NULL UNIQUE,
                        BALANCE    DECIMAL(18,2) NOT NULL DEFAULT 0
);

CREATE TABLE LEDGER (
                        ID             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        VERSION        INT,
                        CREATED_AT     TIMESTAMP,
                        UPDATED_AT     TIMESTAMP,

                        WALLET_ID      BIGINT         NOT NULL,
                        AMOUNT         DECIMAL(18,2)  NOT NULL,
                        OPERATION_TYPE VARCHAR(20)    NOT NULL,  -- enum as string
                        REF            VARCHAR(100)   NOT NULL
);

CREATE TABLE AUDIT_LOG (
                           ID         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           VERSION    INT,
                           CREATED_AT TIMESTAMP,
                           UPDATED_AT TIMESTAMP,

                           USERNAME   VARCHAR(64)   NOT NULL,
                           OPERATION  VARCHAR(32)   NOT NULL,
                           AMOUNT     DECIMAL(18,2),
                           REF        VARCHAR(100),
                           DETAILS    VARCHAR(200),
                           REQUEST_ID VARCHAR(40)
);

CREATE TABLE ACCOUNT_LIMIT_CONFIG (
                                      ID              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      VERSION         INT,
                                      CREATED_AT      TIMESTAMP,
                                      UPDATED_AT      TIMESTAMP,

                                      USER_ID         BIGINT         NOT NULL UNIQUE,
                                      DAILY_LIMIT     DECIMAL(18,2)  NOT NULL,
                                      SINGLE_TX_LIMIT DECIMAL(18,2)  NOT NULL
);

CREATE TABLE ACCOUNT_LIMIT_USAGE (
                                     ID          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     VERSION     INT,
                                     CREATED_AT  TIMESTAMP,
                                     UPDATED_AT  TIMESTAMP,

                                     USER_ID     BIGINT         NOT NULL,
                                     DATE        DATE           NOT NULL,
                                     USED_AMOUNT DECIMAL(18,2)  NOT NULL,
                                     LAST_TX_ID  UUID
);

-- =========================
-- FKs
-- =========================
ALTER TABLE WALLET
    ADD CONSTRAINT FK_WALLET_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

ALTER TABLE LEDGER
    ADD CONSTRAINT FK_LEDGER_WALLET
        FOREIGN KEY (WALLET_ID) REFERENCES WALLET(ID);

ALTER TABLE ACCOUNT_LIMIT_CONFIG
    ADD CONSTRAINT FK_ALC_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

ALTER TABLE ACCOUNT_LIMIT_USAGE
    ADD CONSTRAINT FK_ALU_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

-- =========================
-- INDEXES & UNIQUES
-- =========================
CREATE UNIQUE INDEX ix_ledger_wallet_ref ON LEDGER (WALLET_ID, REF);
CREATE INDEX ix_ledger_ref ON LEDGER (REF);

CREATE INDEX ix_audit_user ON AUDIT_LOG (USERNAME);

CREATE UNIQUE INDEX ux_alu_user_date ON ACCOUNT_LIMIT_USAGE (USER_ID, DATE);

